"""
Luna Creative Associations System
Concept pruning, reinforcement learning for creativity, and lateral thinking

Key Concepts:
- Divergent Thinking: Generate multiple creative solutions
- Lateral Thinking: Connect seemingly unrelated concepts
- Conceptual Blending: Merge concepts to create novel ideas
- Remote Associations: Find distant conceptual connections
- Creative Pruning: Remove obvious/boring associations
- Reinforcement Learning: Reward novel and valuable ideas
- Analogical Reasoning: Transfer knowledge across domains
- Bisociation: Connect two unrelated matrices of thought
- Serendipitous Discovery: Find unexpected connections
- Combinatorial Creativity: Combine existing ideas in novel ways

Based on creativity research by:
- Arthur Koestler (Bisociation Theory)
- Edward de Bono (Lateral Thinking)
- Gilles Fauconnier & Mark Turner (Conceptual Blending)
- Sarnoff Mednick (Remote Associates Test)

This creates true creative intelligence with novel idea generation.
"""

import time
import json
import sqlite3
import threading
import numpy as np
from typing import Dict, List, Optional, Tuple, Any, Set
from datetime import datetime, timedelta
from dataclasses import dataclass
from enum import Enum
import math
import random
from collections import defaultdict, deque
import itertools

class AssociationType(Enum):
    """Types of creative associations"""
    DIRECT = "direct"                    # A → B (obvious)
    ANALOGICAL = "analogical"            # A is like B
    REMOTE = "remote"                    # A ⟹ B (distant)
    LATERAL = "lateral"                  # A ⊥ B (perpendicular)
    BISOCIATIVE = "bisociative"         # A ∩ B (intersection)
    BLENDED = "blended"                  # A + B = C (new concept)
    SERENDIPITOUS = "serendipitous"     # A ? B (unexpected)

class CreativityLevel(Enum):
    """Creativity levels"""
    CONVENTIONAL = "conventional"        # 0.0-0.3
    NOVEL = "novel"                     # 0.3-0.6
    CREATIVE = "creative"               # 0.6-0.8
    HIGHLY_CREATIVE = "highly_creative" # 0.8-0.95
    REVOLUTIONARY = "revolutionary"      # 0.95-1.0

@dataclass
class ConceptNode:
    """A concept in the creative association network"""
    concept_id: str
    concept: str
    domain: str
    activation: float  # 0.0 to 1.0
    novelty: float  # 0.0 to 1.0
    utility: float  # 0.0 to 1.0
    timestamp: float

@dataclass
class CreativeAssociation:
    """An association between concepts"""
    association_id: str
    concept_a: str
    concept_b: str
    association_type: AssociationType
    strength: float  # 0.0 to 1.0
    novelty: float  # 0.0 to 1.0
    utility: float  # 0.0 to 1.0
    creativity_score: float  # Combined score
    context: str
    timestamp: float
    reinforcement_count: int = 0
    last_reinforcement: Optional[float] = None

@dataclass
class CreativeIdea:
    """A creative idea generated by Luna"""
    idea_id: str
    idea_content: str
    source_concepts: List[str]
    association_path: List[str]
    creativity_level: CreativityLevel
    novelty_score: float
    utility_score: float
    originality_score: float
    timestamp: float

class LunaCreativeAssociations:
    """
    Creative Associations System
    
    Implements:
    - Divergent thinking and idea generation
    - Lateral thinking techniques
    - Conceptual blending
    - Remote association detection
    - Creative pruning of obvious ideas
    - Reinforcement learning for creativity
    """
    
    def __init__(self, ollama_chat_func):
        self.ollama_chat = ollama_chat_func
        
        # Concept network
        self.concepts: Dict[str, ConceptNode] = {}
        self.associations: Dict[str, CreativeAssociation] = {}
        
        # Association graph (for finding creative paths)
        self.association_graph = defaultdict(list)  # concept → [connected concepts]
        
        # Creative ideas generated
        self.creative_ideas = deque(maxlen=500)
        
        # Pruning thresholds
        self.obviousness_threshold = 0.7  # Prune if too obvious
        self.novelty_threshold = 0.3  # Keep if novel enough
        
        # Reinforcement learning
        self.creativity_rewards = {}  # idea_id → reward
        self.association_rewards = {}  # association_id → reward
        
        # Statistics
        self.total_associations_generated = 0
        self.total_associations_pruned = 0
        self.total_creative_ideas = 0
        
        # Database
        self.db_path = "luna_creative_associations.db"
        self._initialize_database()
        
        print("⚙️ Luna Creative Associations System initialized")
        print("   🎨 Divergent Thinking: Generates multiple creative solutions")
        print("   🔀 Lateral Thinking: Connects unrelated concepts")
        print("   ✨ Conceptual Blending: Merges ideas to create novelty")
        print("   🌟 Remote Associations: Finds distant connections")
        print("   ✂️ Creative Pruning: Removes obvious/boring ideas")
        print("   🏆 Reinforcement Learning: Rewards novel and valuable creativity")
    
    def _initialize_database(self):
        """Initialize creative associations database"""
        try:
            conn = sqlite3.connect(self.db_path)
            cursor = conn.cursor()
            
            # Concepts table
            cursor.execute('''
                CREATE TABLE IF NOT EXISTS concepts (
                    concept_id TEXT PRIMARY KEY,
                    concept TEXT,
                    domain TEXT,
                    activation REAL,
                    novelty REAL,
                    utility REAL,
                    timestamp REAL
                )
            ''')
            
            # Associations table
            cursor.execute('''
                CREATE TABLE IF NOT EXISTS associations (
                    association_id TEXT PRIMARY KEY,
                    concept_a TEXT,
                    concept_b TEXT,
                    association_type TEXT,
                    strength REAL,
                    novelty REAL,
                    utility REAL,
                    creativity_score REAL,
                    context TEXT,
                    timestamp REAL,
                    reinforcement_count INTEGER,
                    last_reinforcement REAL
                )
            ''')
            
            # Creative ideas table
            cursor.execute('''
                CREATE TABLE IF NOT EXISTS creative_ideas (
                    idea_id TEXT PRIMARY KEY,
                    idea_content TEXT,
                    source_concepts TEXT,
                    association_path TEXT,
                    creativity_level TEXT,
                    novelty_score REAL,
                    utility_score REAL,
                    originality_score REAL,
                    timestamp REAL
                )
            ''')
            
            conn.commit()
            conn.close()
            print("⚙️ Creative Associations database initialized")
            
        except Exception as e:
            print(f"⚠️ Creative Associations database error: {e}")
    
    def add_concept(self, concept: str, domain: str = "general") -> ConceptNode:
        """Add a concept to the network"""
        try:
            concept_id = f"concept_{concept.replace(' ', '_').lower()}_{int(time.time() * 1000) % 10000}"
            
            node = ConceptNode(
                concept_id=concept_id,
                concept=concept,
                domain=domain,
                activation=0.5,
                novelty=0.5,
                utility=0.5,
                timestamp=time.time()
            )
            
            self.concepts[concept_id] = node
            self._save_concept(node)
            
            return node
            
        except Exception as e:
            print(f"⚠️ Concept addition error: {e}")
            return None
    
    def generate_creative_associations(self, seed_concept: str, context: str = "general",
                                     num_associations: int = 5) -> List[CreativeAssociation]:
        """Generate creative associations for a concept"""
        try:
            print(f"🎨 Generating creative associations for: '{seed_concept}'")
            
            # Generate associations using Ollama
            associations = self._generate_associations_with_ollama(seed_concept, context, num_associations)
            
            # Prune obvious associations
            creative_associations = self._prune_obvious_associations(associations)
            
            # Store creative associations
            for assoc in creative_associations:
                self.associations[assoc.association_id] = assoc
                self._save_association(assoc)
                
                # Update association graph
                self.association_graph[assoc.concept_a].append(assoc.concept_b)
                self.association_graph[assoc.concept_b].append(assoc.concept_a)
            
            self.total_associations_generated += len(creative_associations)
            
            print(f"🎨 Generated {len(creative_associations)} creative associations (pruned {len(associations) - len(creative_associations)} obvious ones)")
            
            return creative_associations
            
        except Exception as e:
            print(f"⚠️ Creative association generation error: {e}")
            return []
    
    def _generate_associations_with_ollama(self, seed_concept: str, context: str,
                                          num_associations: int) -> List[CreativeAssociation]:
        """Generate associations using Ollama for creativity"""
        try:
            prompt = f"""You are Luna, a highly creative AI engaging in lateral thinking.

Seed Concept: "{seed_concept}"
Context: {context}

Generate {num_associations} CREATIVE associations with this concept. Don't just give obvious connections - think laterally, creatively, and make unexpected connections!

For each association, explain:
1. The connected concept
2. The type of connection (direct/analogical/remote/lateral/bisociative/blended/serendipitous)
3. Why this connection is interesting or creative

Be creative! Think outside the box! Make unexpected connections!

Format:
CONCEPT: [concept name]
TYPE: [connection type]
REASON: [why interesting]

Generate {num_associations} creative associations:"""

            response = self.ollama_chat(
                model='hf.co/NousResearch/Nous-Hermes-2-Mistral-7B-DPO-GGUF:Q5_K_M',
                messages=[{'role': 'user', 'content': prompt}],
                options={'temperature': 0.95, 'num_predict': 500, 'stop': ['\n\n\n']}
            )
            
            if response and response.get('message', {}).get('content'):
                associations_text = response['message']['content'].strip()
                
                # Parse associations
                associations = self._parse_associations(seed_concept, associations_text, context)
                
                return associations
                
        except Exception as e:
            print(f"⚠️ Ollama association generation error: {e}")
            return []
    
    def _parse_associations(self, seed_concept: str, associations_text: str, context: str) -> List[CreativeAssociation]:
        """Parse associations from Ollama response"""
        associations = []
        
        try:
            lines = associations_text.split('\n')
            current_concept = None
            current_type = None
            current_reason = None
            
            for line in lines:
                line = line.strip()
                
                if line.startswith('CONCEPT:'):
                    current_concept = line.split(':', 1)[1].strip()
                elif line.startswith('TYPE:'):
                    current_type = line.split(':', 1)[1].strip().lower()
                elif line.startswith('REASON:'):
                    current_reason = line.split(':', 1)[1].strip()
                    
                    # Create association
                    if current_concept and current_type:
                        # Determine association type
                        assoc_type = AssociationType.REMOTE
                        if 'direct' in current_type:
                            assoc_type = AssociationType.DIRECT
                        elif 'analogical' in current_type or 'analogy' in current_type:
                            assoc_type = AssociationType.ANALOGICAL
                        elif 'lateral' in current_type:
                            assoc_type = AssociationType.LATERAL
                        elif 'bisociative' in current_type:
                            assoc_type = AssociationType.BISOCIATIVE
                        elif 'blended' in current_type or 'blend' in current_type:
                            assoc_type = AssociationType.BLENDED
                        elif 'serendipitous' in current_type or 'unexpected' in current_type:
                            assoc_type = AssociationType.SERENDIPITOUS
                        
                        # Calculate scores
                        novelty = self._calculate_novelty(seed_concept, current_concept, assoc_type)
                        utility = self._calculate_utility(current_reason if current_reason else "")
                        creativity = (novelty * 0.6 + utility * 0.4)
                        
                        association = CreativeAssociation(
                            association_id=f"assoc_{int(time.time() * 1000)}_{random.randint(1000, 9999)}",
                            concept_a=seed_concept,
                            concept_b=current_concept,
                            association_type=assoc_type,
                            strength=0.7,
                            novelty=novelty,
                            utility=utility,
                            creativity_score=creativity,
                            context=context,
                            timestamp=time.time()
                        )
                        
                        associations.append(association)
                        
                        # Reset for next association
                        current_concept = None
                        current_type = None
                        current_reason = None
            
        except Exception as e:
            print(f"⚠️ Association parsing error: {e}")
        
        return associations
    
    def _calculate_novelty(self, concept_a: str, concept_b: str, assoc_type: AssociationType) -> float:
        """Calculate novelty score for an association"""
        # Base novelty by association type
        type_novelty = {
            AssociationType.DIRECT: 0.1,
            AssociationType.ANALOGICAL: 0.4,
            AssociationType.REMOTE: 0.7,
            AssociationType.LATERAL: 0.8,
            AssociationType.BISOCIATIVE: 0.85,
            AssociationType.BLENDED: 0.9,
            AssociationType.SERENDIPITOUS: 0.95
        }
        
        base_novelty = type_novelty.get(assoc_type, 0.5)
        
        # Reduce novelty if association already exists
        for assoc in self.associations.values():
            if (assoc.concept_a == concept_a and assoc.concept_b == concept_b) or \
               (assoc.concept_a == concept_b and assoc.concept_b == concept_a):
                base_novelty *= 0.5  # 50% less novel if already exists
        
        return min(1.0, base_novelty + random.uniform(-0.1, 0.1))
    
    def _calculate_utility(self, reason: str) -> float:
        """Calculate utility score from reason"""
        # Simple heuristic based on reason quality
        utility_keywords = {
            'useful': 0.8,
            'valuable': 0.8,
            'important': 0.7,
            'interesting': 0.6,
            'creative': 0.7,
            'novel': 0.7,
            'unique': 0.8,
            'innovative': 0.9
        }
        
        max_utility = 0.5  # Base utility
        for keyword, value in utility_keywords.items():
            if keyword in reason.lower():
                max_utility = max(max_utility, value)
        
        return max_utility
    
    def _prune_obvious_associations(self, associations: List[CreativeAssociation]) -> List[CreativeAssociation]:
        """Prune obvious/boring associations, keep creative ones"""
        creative_associations = []
        
        for assoc in associations:
            # Prune if too obvious (direct associations with low novelty)
            if assoc.association_type == AssociationType.DIRECT and assoc.novelty < self.novelty_threshold:
                print(f"✂️ Pruned obvious: {assoc.concept_a} → {assoc.concept_b}")
                self.total_associations_pruned += 1
                continue
            
            # Keep if creative enough
            if assoc.creativity_score >= self.novelty_threshold:
                creative_associations.append(assoc)
            else:
                print(f"✂️ Pruned uncreative: {assoc.concept_a} → {assoc.concept_b} (score: {assoc.creativity_score:.2f})")
                self.total_associations_pruned += 1
        
        return creative_associations
    
    def generate_creative_idea(self, problem: str, context: str = "general") -> Optional[CreativeIdea]:
        """Generate a creative idea using lateral thinking"""
        try:
            print(f"💡 Generating creative idea for: '{problem}'")
            
            # Extract key concepts from problem
            concepts = self._extract_concepts(problem)
            
            # Generate remote associations
            associations = []
            for concept in concepts[:3]:  # Use top 3 concepts
                assocs = self.generate_creative_associations(concept, context, num_associations=3)
                associations.extend(assocs)
            
            # Generate creative idea using Ollama with lateral thinking
            idea_content = self._generate_creative_idea_with_ollama(problem, associations, context)
            
            if idea_content:
                # Calculate creativity metrics
                novelty = self._assess_idea_novelty(idea_content)
                utility = self._assess_idea_utility(idea_content, problem)
                originality = self._assess_idea_originality(idea_content, associations)
                
                # Determine creativity level
                creativity_score = (novelty * 0.4 + utility * 0.3 + originality * 0.3)
                creativity_level = self._determine_creativity_level(creativity_score)
                
                # Create creative idea
                idea = CreativeIdea(
                    idea_id=f"idea_{int(time.time() * 1000)}_{random.randint(1000, 9999)}",
                    idea_content=idea_content,
                    source_concepts=concepts,
                    association_path=[a.association_id for a in associations],
                    creativity_level=creativity_level,
                    novelty_score=novelty,
                    utility_score=utility,
                    originality_score=originality,
                    timestamp=time.time()
                )
                
                self.creative_ideas.append(idea)
                self._save_creative_idea(idea)
                self.total_creative_ideas += 1
                
                print(f"💡 Creative idea generated: creativity={creativity_score:.2f}, level={creativity_level.value}")
                
                return idea
                
        except Exception as e:
            print(f"⚠️ Creative idea generation error: {e}")
            return None
    
    def _extract_concepts(self, text: str) -> List[str]:
        """Extract key concepts from text"""
        # Simple keyword extraction (could be enhanced with NLP)
        words = text.lower().split()
        
        # Filter meaningful words
        stop_words = {'the', 'a', 'an', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for', 'of', 'with'}
        concepts = [w for w in words if len(w) > 3 and w not in stop_words]
        
        return concepts[:5]  # Top 5 concepts
    
    def _generate_creative_idea_with_ollama(self, problem: str, associations: List[CreativeAssociation], context: str) -> str:
        """Generate creative idea using Ollama with lateral thinking"""
        try:
            # Format associations for prompt
            assoc_text = ""
            for assoc in associations[:5]:
                assoc_text += f"- {assoc.concept_a} → {assoc.concept_b} ({assoc.association_type.value})\n"
            
            prompt = f"""You are Luna, engaging in highly creative lateral thinking.

Problem/Challenge: "{problem}"
Context: {context}

Creative Associations to Use:
{assoc_text}

Use LATERAL THINKING to generate a creative solution or idea. Don't think conventionally - 
think sideways, make unexpected connections, blend concepts in novel ways!

Apply Edward de Bono's lateral thinking techniques:
- Challenge assumptions
- Explore alternatives
- Make random connections
- Use provocative thinking
- Find hidden patterns

Generate ONE highly creative idea (2-3 sentences). Be bold, be innovative, be Luna thinking creatively!"""

            response = self.ollama_chat(
                model='hf.co/NousResearch/Nous-Hermes-2-Mistral-7B-DPO-GGUF:Q5_K_M',
                messages=[{'role': 'user', 'content': prompt}],
                options={'temperature': 0.95, 'num_predict': 200, 'stop': ['\n\n']}
            )
            
            if response and response.get('message', {}).get('content'):
                idea = response['message']['content'].strip()
                print(f"💡 Creative idea: {idea[:100]}...")
                return idea
                
        except Exception as e:
            print(f"⚠️ Ollama creative idea generation error: {e}")
        
        return ""
    
    def _assess_idea_novelty(self, idea: str) -> float:
        """Assess how novel an idea is"""
        # Check if similar ideas already exist
        novelty = 0.8  # Base novelty
        
        for existing_idea in self.creative_ideas:
            # Simple similarity check
            idea_words = set(idea.lower().split())
            existing_words = set(existing_idea.idea_content.lower().split())
            
            overlap = len(idea_words.intersection(existing_words))
            similarity = overlap / max(len(idea_words), len(existing_words))
            
            if similarity > 0.5:
                novelty *= 0.7  # Reduce novelty if similar idea exists
        
        return max(0.1, min(1.0, novelty))
    
    def _assess_idea_utility(self, idea: str, problem: str) -> float:
        """Assess how useful an idea is"""
        # Check if idea addresses the problem
        problem_words = set(problem.lower().split())
        idea_words = set(idea.lower().split())
        
        relevance = len(problem_words.intersection(idea_words)) / max(len(problem_words), 1)
        
        # Base utility on relevance and length
        utility = relevance * 0.7 + min(1.0, len(idea) / 200.0) * 0.3
        
        return max(0.1, min(1.0, utility))
    
    def _assess_idea_originality(self, idea: str, associations: List[CreativeAssociation]) -> float:
        """Assess how original an idea is"""
        # Higher originality if uses more remote/lateral associations
        if not associations:
            return 0.5
        
        originality_scores = []
        for assoc in associations:
            type_originality = {
                AssociationType.DIRECT: 0.1,
                AssociationType.ANALOGICAL: 0.4,
                AssociationType.REMOTE: 0.7,
                AssociationType.LATERAL: 0.85,
                AssociationType.BISOCIATIVE: 0.9,
                AssociationType.BLENDED: 0.95,
                AssociationType.SERENDIPITOUS: 1.0
            }
            originality_scores.append(type_originality.get(assoc.association_type, 0.5))
        
        return np.mean(originality_scores)
    
    def _determine_creativity_level(self, creativity_score: float) -> CreativityLevel:
        """Determine creativity level from score"""
        if creativity_score >= 0.95:
            return CreativityLevel.REVOLUTIONARY
        elif creativity_score >= 0.8:
            return CreativityLevel.HIGHLY_CREATIVE
        elif creativity_score >= 0.6:
            return CreativityLevel.CREATIVE
        elif creativity_score >= 0.3:
            return CreativityLevel.NOVEL
        else:
            return CreativityLevel.CONVENTIONAL
    
    def reinforce_creative_association(self, association_id: str, reward: float):
        """Reinforce a creative association (RL for creativity)"""
        try:
            if association_id not in self.associations:
                return False
            
            assoc = self.associations[association_id]
            
            # Update with reinforcement learning
            old_creativity = assoc.creativity_score
            
            # Reward increases creativity score
            assoc.creativity_score = min(1.0, assoc.creativity_score + reward * 0.1)
            assoc.strength = min(1.0, assoc.strength + reward * 0.15)
            assoc.reinforcement_count += 1
            assoc.last_reinforcement = time.time()
            
            # Store reward
            self.association_rewards[association_id] = reward
            
            # Save
            self._save_association(assoc)
            
            print(f"🏆 Association reinforced: creativity {old_creativity:.2f} → {assoc.creativity_score:.2f}")
            
            return True
            
        except Exception as e:
            print(f"⚠️ Association reinforcement error: {e}")
            return False
    
    def get_creative_statistics(self) -> Dict[str, Any]:
        """Get creative associations statistics"""
        try:
            # Association type distribution
            type_dist = defaultdict(int)
            for assoc in self.associations.values():
                type_dist[assoc.association_type.value] += 1
            
            # Creativity level distribution
            level_dist = defaultdict(int)
            for idea in self.creative_ideas:
                level_dist[idea.creativity_level.value] += 1
            
            # Average scores
            if self.associations:
                avg_novelty = np.mean([a.novelty for a in self.associations.values()])
                avg_utility = np.mean([a.utility for a in self.associations.values()])
                avg_creativity = np.mean([a.creativity_score for a in self.associations.values()])
            else:
                avg_novelty = avg_utility = avg_creativity = 0.0
            
            return {
                'total_concepts': len(self.concepts),
                'total_associations': len(self.associations),
                'total_creative_ideas': self.total_creative_ideas,
                'associations_generated': self.total_associations_generated,
                'associations_pruned': self.total_associations_pruned,
                'pruning_rate': self.total_associations_pruned / max(1, self.total_associations_generated),
                'avg_novelty': avg_novelty,
                'avg_utility': avg_utility,
                'avg_creativity': avg_creativity,
                'association_types': dict(type_dist),
                'creativity_levels': dict(level_dist)
            }
            
        except Exception as e:
            print(f"⚠️ Creative statistics error: {e}")
            return {}
    
    def get_recent_creative_ideas(self, limit: int = 5) -> List[CreativeIdea]:
        """Get recent creative ideas"""
        return list(self.creative_ideas)[-limit:]
    
    def _save_concept(self, node: ConceptNode):
        """Save concept to database"""
        try:
            conn = sqlite3.connect(self.db_path)
            cursor = conn.cursor()
            
            cursor.execute('''
                INSERT OR REPLACE INTO concepts (
                    concept_id, concept, domain, activation, novelty, utility, timestamp
                ) VALUES (?, ?, ?, ?, ?, ?, ?)
            ''', (node.concept_id, node.concept, node.domain, node.activation,
                  node.novelty, node.utility, node.timestamp))
            
            conn.commit()
            conn.close()
            
        except Exception as e:
            print(f"⚠️ Concept save error: {e}")
    
    def _save_association(self, assoc: CreativeAssociation):
        """Save association to database"""
        try:
            conn = sqlite3.connect(self.db_path)
            cursor = conn.cursor()
            
            cursor.execute('''
                INSERT OR REPLACE INTO associations (
                    association_id, concept_a, concept_b, association_type,
                    strength, novelty, utility, creativity_score, context,
                    timestamp, reinforcement_count, last_reinforcement
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ''', (
                assoc.association_id, assoc.concept_a, assoc.concept_b,
                assoc.association_type.value, assoc.strength, assoc.novelty,
                assoc.utility, assoc.creativity_score, assoc.context,
                assoc.timestamp, assoc.reinforcement_count, assoc.last_reinforcement
            ))
            
            conn.commit()
            conn.close()
            
        except Exception as e:
            print(f"⚠️ Association save error: {e}")
    
    def _save_creative_idea(self, idea: CreativeIdea):
        """Save creative idea to database"""
        try:
            conn = sqlite3.connect(self.db_path)
            cursor = conn.cursor()
            
            cursor.execute('''
                INSERT INTO creative_ideas (
                    idea_id, idea_content, source_concepts, association_path,
                    creativity_level, novelty_score, utility_score,
                    originality_score, timestamp
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            ''', (
                idea.idea_id, idea.idea_content,
                json.dumps(idea.source_concepts),
                json.dumps(idea.association_path),
                idea.creativity_level.value,
                idea.novelty_score, idea.utility_score,
                idea.originality_score, idea.timestamp
            ))
            
            conn.commit()
            conn.close()
            
        except Exception as e:
            print(f"⚠️ Creative idea save error: {e}")


# ============================================================================
# GLOBAL INSTANCE
# ============================================================================

creative_associations_system: Optional[LunaCreativeAssociations] = None

def initialize_creative_associations(ollama_chat_func) -> LunaCreativeAssociations:
    """Initialize creative associations system"""
    global creative_associations_system
    if creative_associations_system is None:
        creative_associations_system = LunaCreativeAssociations(ollama_chat_func)
    return creative_associations_system

def get_creative_associations() -> Optional[LunaCreativeAssociations]:
    """Get creative associations system instance"""
    return creative_associations_system

def generate_creative_idea(problem: str, context: str = "general") -> Optional[CreativeIdea]:
    """Generate a creative idea"""
    if creative_associations_system:
        return creative_associations_system.generate_creative_idea(problem, context)
    return None

def generate_lateral_thinking_response(user_input: str, context: str = "general") -> str:
    """Generate a response using lateral thinking"""
    if creative_associations_system:
        idea = creative_associations_system.generate_creative_idea(user_input, context)
        if idea:
            return idea.idea_content
    return ""

